name: Bit Commit Bitmap
on:
  pull_request:
    types:
      - closed
 
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}
      BIT_FEATURES: "cloud-importer-v2"      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize Bit
        uses: bit-tasks/init@v1
      - name: Bit Tag and Export
        run: | 
          bit tag -m "removed pr workflow" --build
          bit export
      - name: Commit Bitmap
        uses: bit-tasks/commit-bitmap@v1
      - name: Bit Lane Cleanup
        uses: bit-tasks/lane-cleanup@v1  