name: Own workflow
on:
  workflow_call:

    secrets:
      BIT_CONFIG_USER_TOKEN:
        required: true
#  pull_request:
#    types:
#      - opened
#      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize Bit
        uses: bit-tasks/init@v1
      - name: Bit Verify
        run: | 
          bit status --strict
          bit build
#      - name: Bit Lane Cleanup
#        uses: bit-tasks/lane-cleanup@v1
#      - name: delete lane
#        run: |
#          bit lane remove flinten.latest/pr-1 --remote --silent                   
      - name: Bit Pull Request
        run: |
          bit status --json
          bit status --strict
          bit lane create pr-1
          bit snap -m first try --build
          bit lane remove flinten.latest/pr-1 --remote --silent --force
          bit export
      - name: Bit Tag and Export
        uses: bit-tasks/tag-export@v1
      - name: Commit Bitmap
        uses: bit-tasks/commit-bitmap@v1